In [1]:
import pandas as pd

df_original = pd.read_csv('FINANSES_original.csv')
df_original.columns

Index(['COU', 'Country', 'SER', 'Service', 'EXP', 'Expression', 'MEASURE',
       'Measure', 'PAR', 'Partner', 'YEA', 'Year', 'Unit Code', 'Unit',
       'PowerCode Code', 'PowerCode', 'Reference Period Code',
       'Reference Period', 'Value', 'Flag Codes', 'Flags'],
      dtype='object')

In [2]:
# DROPPING UNNECESARRY COLUMNS

important_columns = ['Country', 'Partner', 'Value']

df_important_columns = df_original[important_columns].copy()

df_important_columns['Country'] = df_important_columns['Country'].str.lower()
df_important_columns['Partner'] = df_important_columns['Partner'].str.lower()

df_important_columns

        Country    Partner   Value
0       austria  australia    58.5
1       austria    belgium   148.8
2       austria     canada   -19.9
3       austria      chile    45.2
4       austria    czechia    37.2
...         ...        ...     ...
4081  lithuania    ukraine    -6.8
4082  lithuania     latvia   122.7
4083  lithuania      asean    38.9
4084      japan      asean  3778.1
4085    finland      asean   136.8

[4086 rows x 3 columns]

In [3]:
# ABSOLUTE VALUE

df_important_columns['Value'] = df_important_columns['Value'].abs()

df_important_columns

        Country    Partner   Value
0       austria  australia    58.5
1       austria    belgium   148.8
2       austria     canada    19.9
3       austria      chile    45.2
4       austria    czechia    37.2
...         ...        ...     ...
4081  lithuania    ukraine     6.8
4082  lithuania     latvia   122.7
4083  lithuania      asean    38.9
4084      japan      asean  3778.1
4085    finland      asean   136.8

[4086 rows x 3 columns]

In [4]:
# df_important_columns['Country'].unique()
# df_important_columns['Partner'].unique()

In [6]:
df_important_columns.head(10)

   Country    Partner    Value
0  austria  australia     58.5
1  austria    belgium    148.8
2  austria     canada     19.9
3  austria      chile     45.2
4  austria    czechia     37.2
5  austria    denmark    229.8
6  austria    estonia     53.1
7  austria    finland    158.1
8  austria     france    192.6
9  austria    germany  10145.8

In [7]:
df_important_columns[(df_important_columns['Country'] == 'austria') & (df_important_columns['Partner'] == 'denmark')]

   Country  Partner  Value
5  austria  denmark  229.8

In [8]:
df_important_columns[(df_important_columns['Country'] == 'denmark') & (df_important_columns['Partner'] == 'austria')]

     Country  Partner  Value
161  denmark  austria  163.5

In [9]:
repeat_index = df_important_columns[(df_important_columns['Country'] == 'denmark') & (df_important_columns['Partner'] == 'austria')].index
if repeat_index.empty:
    print('pusty')
else:
    print('niepusty')

niepusty

In [10]:
# ONE-DIRECTION FLOW 

def one_direction_flow(df):

    indexes_to_drop = []
    counter = 0
    el = 0

    for index, row in df.iterrows():

        if index in indexes_to_drop:
            continue

        country = row['Country']
        partner = row['Partner']

        repeat_index = df[(df['Country'] == partner) & (df['Partner'] == country)].index

        
        if not repeat_index.empty:

            counter += 1
            print('------------')
            print(country)
            print(partner)
            value = df.loc[repeat_index, 'Value'].values[0]
            print(value)
            print('------------')

            df.at[index, 'Value'] += value

            indexes_to_drop.extend(repeat_index)
        
        else:
            el += 1

    print(counter)
    print(el)
    print(len(indexes_to_drop))
    df = df.drop(indexes_to_drop)

    return df


df_one_direction = one_direction_flow(df_important_columns)

df_one_direction['Value'] = df_one_direction['Value'].round(1)

------------
austria
belgium
358.7
------------
------------
austria
canada
79.7
------------
------------
austria
czechia
472.3
------------
------------
austria
denmark
163.5
------------
------------
austria
estonia
19.1
------------
------------
austria
finland
174.0
------------
------------
austria
france
168.7
------------
------------
austria
germany
10183.0
------------
------------
austria
greece
50.7
------------
------------
austria
hungary
636.8
------------
------------
austria
iceland
11.1
------------
------------
austria
ireland
775.8
------------
------------
austria
italy
91.7
------------
------------
austria
luxembourg
427.8
------------
------------
austria
netherlands
685.5
------------
------------
austria
poland
136.0
------------
------------
austria
portugal
399.9
------------
------------
austria
slovak republic
180.4
------------
------------
austria
slovenia
330.0
------------
------------
austria
spain
645.7
------------
------------
austria
sweden
736.4
------------
------------
austria
united kingdom
760.2
------------
------------
austria
united states
435.0
------------
------------
austria
russia
917.9
------------
------------
austria
latvia
10.6
------------
------------
austria
lithuania
157.0
------------
------------
germany
united kingdom
8959.6
------------
------------
germany
finland
819.7
------------
------------
belgium
slovenia
118.9
------------
------------
estonia
sweden
86.2
------------
------------
estonia
new zealand
0.8
------------
------------
finland
czechia
101.9
------------
------------
estonia
germany
336.1
------------
------------
czechia
greece
171.0
------------
------------
czechia
lithuania
10.9
------------
------------
estonia
latvia
93.0
------------
------------
finland
poland
356.3
------------
------------
denmark
portugal
211.2
------------
------------
denmark
united kingdom
2994.7
------------
------------
france
slovenia
38.0
------------
------------
france
canada
169.3
------------
------------
belgium
new zealand
10.8
------------
------------
germany
slovenia
363.3
------------
------------
czechia
france
714.7
------------
------------
czechia
spain
459.7
------------
------------
denmark
spain
1559.7
------------
------------
czechia
netherlands
193.0
------------
------------
belgium
denmark
365.4
------------
------------
germany
greece
3756.1
------------
------------
czechia
slovenia
37.3
------------
------------
estonia
slovak republic
0.7
------------
------------
estonia
luxembourg
87.7
------------
------------
france
finland
159.4
------------
------------
belgium
greece
471.1
------------
------------
finland
slovenia
1.6
------------
------------
belgium
portugal
399.9
------------
------------
czechia
denmark
65.4
------------
------------
germany
lithuania
473.8
------------
------------
denmark
finland
698.8
------------
------------
czechia
portugal
25.2
------------
------------
france
denmark
625.7
------------
------------
france
portugal
2456.4
------------
------------
france
greece
1664.3
------------
------------
finland
luxembourg
564.6
------------
------------
belgium
russia
369.1
------------
------------
finland
greece
180.7
------------
------------
belgium
sweden
260.6
------------
------------
finland
lithuania
43.7
------------
------------
germany
ireland
8838.5
------------
------------
czechia
italy
18.9
------------
------------
estonia
italy
19.8
------------
------------
belgium
france
2396.6
------------
------------
germany
russia
3360.5
------------
------------
france
iceland
98.3
------------
------------
belgium
spain
2053.9
------------
------------
denmark
luxembourg
57.1
------------
------------
czechia
czechia
0.0
------------
------------
denmark
slovenia
7.2
------------
------------
finland
hungary
223.8
------------
------------
germany
canada
335.8
------------
------------
germany
united states
4740.0
------------
------------
germany
slovak republic
94.2
------------
------------
czechia
poland
249.5
------------
------------
denmark
hungary
47.6
------------
------------
belgium
netherlands
2295.3
------------
------------
germany
belgium
658.9
------------
------------
germany
netherlands
6097.4
------------
------------
denmark
netherlands
1364.5
------------
------------
france
russia
3220.9
------------
------------
estonia
united states
30.0
------------
------------
estonia
slovenia
1.3
------------
------------
france
spain
7838.2
------------
------------
denmark
russia
275.2
------------
------------
estonia
united kingdom
78.9
------------
------------
czechia
russia
1044.7
------------
------------
france
netherlands
1572.1
------------
------------
czechia
belgium
342.8
------------
------------
estonia
finland
887.4
------------
------------
finland
united states
788.0
------------
------------
germany
japan
1529.7
------------
------------
denmark
canada
7.2
------------
------------
france
new zealand
168.4
------------
------------
finland
belgium
194.0
------------
------------
belgium
hungary
20.2
------------
------------
denmark
new zealand
479.5
------------
------------
belgium
poland
255.2
------------
------------
finland
ireland
867.5
------------
------------
czechia
ireland
183.3
------------
------------
france
australia
663.4
------------
------------
finland
russia
2801.7
------------
------------
belgium
australia
0.9
------------
------------
finland
netherlands
988.0
------------
------------
belgium
latvia
67.8
------------
------------
germany
czechia
535.9
------------
------------
estonia
lithuania
18.2
------------
------------
france
poland
106.2
------------
------------
czechia
hungary
62.1
------------
------------
france
hungary
23.9
------------
------------
germany
poland
4683.4
------------
------------
france
lithuania
198.4
------------
------------
czechia
united kingdom
345.5
------------
------------
germany
iceland
140.6
------------
------------
denmark
greece
149.1
------------
------------
estonia
czechia
12.7
------------
------------
denmark
iceland
50.0
------------
------------
france
united kingdom
5244.1
------------
------------
germany
portugal
1580.9
------------
------------
belgium
iceland
0.1
------------
------------
finland
new zealand
10.0
------------
------------
finland
canada
4.5
------------
------------
germany
denmark
470.3
------------
------------
belgium
united kingdom
1234.1
------------
------------
estonia
poland
44.7
------------
------------
denmark
lithuania
161.9
------------
------------
czechia
sweden
130.5
------------
------------
finland
portugal
166.1
------------
------------
belgium
italy
89.9
------------
------------
denmark
ireland
985.7
------------
------------
estonia
belgium
17.3
------------
------------
germany
spain
9116.2
------------
------------
france
united states
1566.0
------------
------------
estonia
russia
280.9
------------
------------
denmark
united states
711.0
------------
------------
estonia
ireland
18.6
------------
------------
germany
france
597.8
------------
------------
estonia
netherlands
28.7
------------
------------
belgium
japan
1030.1
------------
------------
czechia
latvia
10.6
------------
------------
france
ireland
4224.6
------------
------------
germany
new zealand
277.9
------------
------------
france
japan
719.0
------------
------------
czechia
iceland
1.6
------------
------------
france
italy
1421.6
------------
------------
finland
spain
981.8
------------
------------
czechia
luxembourg
182.0
------------
------------
denmark
poland
242.5
------------
------------
belgium
slovak republic
6.6
------------
------------
belgium
luxembourg
4268.5
------------
------------
germany
hungary
436.1
------------
------------
estonia
greece
41.4
------------
------------
germany
italy
2001.8
------------
------------
denmark
italy
67.1
------------
------------
estonia
hungary
36.8
------------
------------
finland
sweden
1122.9
------------
------------
finland
latvia
46.5
------------
------------
france
estonia
50.4
------------
------------
denmark
estonia
19.9
------------
------------
belgium
united states
24.0
------------
------------
france
luxembourg
4803.9
------------
------------
france
slovak republic
7.8
------------
------------
belgium
ireland
813.0
------------
------------
finland
united kingdom
1283.5
------------
------------
finland
iceland
50.1
------------
------------
belgium
lithuania
109.9
------------
------------
denmark
slovak republic
54.9
------------
------------
estonia
spain
73.1
------------
------------
estonia
portugal
13.3
------------
------------
denmark
latvia
61.1
------------
------------
germany
latvia
156.8
------------
------------
finland
slovak republic
9.3
------------
------------
czechia
united states
177.0
------------
------------
czechia
slovak republic
56.3
------------
------------
france
sweden
947.4
------------
------------
denmark
sweden
489.8
------------
------------
germany
sweden
602.2
------------
------------
france
latvia
150.1
------------
------------
germany
australia
1216.0
------------
------------
finland
italy
145.6
------------
------------
germany
luxembourg
3790.2
------------
------------
luxembourg
new zealand
0.8
------------
------------
ireland
slovenia
30.3
------------
------------
latvia
slovak republic
1.3
------------
------------
latvia
ireland
57.1
------------
------------
ireland
canada
974.0
------------
------------
greece
poland
394.3
------------
------------
luxembourg
latvia
14.6
------------
------------
iceland
poland
5.0
------------
------------
greece
hungary
14.7
------------
------------
luxembourg
sweden
155.3
------------
------------
ireland
sweden
1119.4
------------
------------
italy
japan
1310.1
------------
------------
hungary
slovak republic
22.1
------------
------------
italy
sweden
532.2
------------
------------
luxembourg
hungary
21.4
------------
------------
latvia
italy
248.7
------------
------------
iceland
slovenia
1.6
------------
------------
hungary
slovenia
138.3
------------
------------
greece
slovenia
7.4
------------
------------
ireland
united kingdom
7016.2
------------
------------
italy
iceland
13.8
------------
------------
italy
slovenia
782.2
------------
------------
hungary
sweden
244.0
------------
------------
luxembourg
spain
175.4
------------
------------
hungary
latvia
9.3
------------
------------
iceland
greece
3.9
------------
------------
latvia
portugal
6.6
------------
------------
iceland
russia
11.3
------------
------------
latvia
iceland
0.8
------------
------------
hungary
lithuania
17.4
------------
------------
hungary
united kingdom
24.8
------------
------------
luxembourg
italy
3946.0
------------
------------
latvia
united kingdom
1.6
------------
------------
italy
greece
381.8
------------
------------
luxembourg
portugal
203.3
------------
------------
greece
lithuania
93.7
------------
------------
italy
lithuania
87.0
------------
------------
ireland
lithuania
96.3
------------
------------
latvia
new zealand
0.8
------------
------------
ireland
italy
3354.7
------------
------------
iceland
lithuania
0.7
------------
------------
luxembourg
united kingdom
1994.3
------------
------------
luxembourg
iceland
1.5
------------
------------
greece
ireland
855.6
------------
------------
greece
united states
1358.0
------------
------------
hungary
united states
393.0
------------
------------
ireland
slovak republic
109.7
------------
------------
ireland
united states
26713.0
------------
------------
italy
slovak republic
220.4
------------
------------
hungary
poland
70.4
------------
------------
italy
new zealand
4.1
------------
------------
italy
canada
607.4
------------
------------
ireland
australia
532.7
------------
------------
latvia
sweden
76.1
------------
------------
greece
netherlands
314.7
------------
------------
italy
poland
300.8
------------
------------
greece
russia
2237.3
------------
------------
iceland
netherlands
89.8
------------
------------
italy
russia
2247.4
------------
------------
ireland
luxembourg
1612.8
------------
------------
latvia
russia
226.2
------------
------------
luxembourg
japan
369.1
------------
------------
latvia
netherlands
13.6
------------
------------
greece
spain
233.8
------------
------------
italy
united states
947.0
------------
------------
iceland
slovak republic
0.1
------------
------------
hungary
italy
354.6
------------
------------
italy
portugal
442.4
------------
------------
luxembourg
slovak republic
8.5
------------
------------
greece
sweden
201.6
------------
------------
italy
united kingdom
4846.0
------------
------------
iceland
sweden
23.6
------------
------------
luxembourg
united states
5639.0
------------
------------
luxembourg
lithuania
27.8
------------
------------
ireland
netherlands
13741.5
------------
------------
ireland
russia
1425.0
------------
------------
iceland
united kingdom
6.5
------------
------------
greece
slovak republic
37.3
------------
------------
ireland
poland
56.4
------------
------------
hungary
netherlands
222.0
------------
------------
italy
australia
869.0
------------
------------
hungary
russia
212.3
------------
------------
latvia
united states
75.0
------------
------------
greece
australia
794.1
------------
------------
greece
luxembourg
33.2
------------
------------
luxembourg
poland
60.2
------------
------------
latvia
lithuania
122.7
------------
------------
latvia
greece
98.2
------------
------------
ireland
portugal
199.3
------------
------------
greece
new zealand
9.1
------------
------------
luxembourg
russia
814.9
------------
------------
luxembourg
netherlands
1013.2
------------
------------
greece
canada
678.9
------------
------------
italy
spain
2614.5
------------
------------
ireland
spain
30.6
------------
------------
latvia
slovenia
4.5
------------
------------
italy
netherlands
50.0
------------
------------
hungary
portugal
71.7
------------
------------
iceland
portugal
4.0
------------
------------
greece
united kingdom
1655.4
------------
------------
greece
portugal
33.2
------------
------------
iceland
spain
77.1
------------
------------
luxembourg
slovenia
30.6
------------
------------
latvia
poland
87.1
------------
------------
hungary
spain
244.4
------------
------------
netherlands
australia
749.1
------------
------------
netherlands
canada
1149.6
------------
------------
netherlands
japan
836.8
------------
------------
netherlands
new zealand
12.4
------------
------------
netherlands
poland
795.1
------------
------------
netherlands
portugal
612.4
------------
------------
netherlands
slovak republic
255.7
------------
------------
netherlands
slovenia
104.3
------------
------------
netherlands
spain
3727.8
------------
------------
netherlands
sweden
52.6
------------
------------
netherlands
united kingdom
16056.5
------------
------------
netherlands
united states
7509.0
------------
------------
netherlands
russia
1780.6
------------
------------
netherlands
lithuania
166.9
------------
------------
poland
canada
17.2
------------
------------
poland
portugal
90.3
------------
------------
poland
slovak republic
73.6
------------
------------
poland
slovenia
3.9
------------
------------
poland
spain
702.8
------------
------------
poland
sweden
884.9
------------
------------
poland
united kingdom
31.3
------------
------------
poland
united states
947.0
------------
------------
poland
russia
170.3
------------
------------
poland
lithuania
36.8
------------
------------
portugal
canada
142.1
------------
------------
portugal
new zealand
2.5
------------
------------
portugal
slovak republic
63.2
------------
------------
portugal
slovenia
0.9
------------
------------
portugal
spain
1118.6
------------
------------
portugal
sweden
23.7
------------
------------
portugal
united kingdom
1591.2
------------
------------
portugal
united states
445.0
------------
------------
portugal
russia
78.7
------------
------------
portugal
lithuania
9.8
------------
------------
slovak republic
new zealand
4.1
------------
------------
slovak republic
slovenia
13.2
------------
------------
slovak republic
spain
41.2
------------
------------
slovak republic
sweden
16.2
------------
------------
slovak republic
united kingdom
3.3
------------
------------
slovak republic
united states
218.0
------------
------------
slovak republic
russia
124.4
------------
------------
slovak republic
lithuania
8.5
------------
------------
spain
canada
294.2
------------
------------
spain
japan
337.2
------------
------------
spain
new zealand
19.9
------------
------------
spain
slovenia
8.9
------------
------------
spain
sweden
813.9
------------
------------
spain
united kingdom
9041.8
------------
------------
spain
united states
1836.0
------------
------------
spain
russia
3191.0
------------
------------
spain
lithuania
60.0
------------
------------
slovenia
new zealand
0.8
------------
------------
slovenia
slovenia
0.0
------------
------------
slovenia
sweden
26.7
------------
------------
slovenia
united kingdom
13.1
------------
------------
slovenia
united states
134.0
------------
------------
slovenia
russia
80.1
------------
------------
slovenia
lithuania
8.2
------------
------------
sweden
australia
77.5
------------
------------
sweden
canada
354.8
------------
------------
sweden
japan
263.8
------------
------------
sweden
new zealand
25.7
------------
------------
sweden
united kingdom
3496.6
------------
------------
sweden
united states
3552.0
------------
------------
sweden
russia
354.7
------------
------------
sweden
lithuania
23.5
------------
------------
united kingdom
australia
1810.9
------------
------------
united kingdom
canada
358.5
------------
------------
united kingdom
japan
3781.2
------------
------------
united kingdom
new zealand
249.7
------------
------------
united kingdom
united states
10025.0
------------
------------
united kingdom
russia
1715.4
------------
------------
united kingdom
lithuania
11.0
------------
------------
australia
canada
622.8
------------
------------
australia
japan
54.3
------------
------------
australia
new zealand
945.7
------------
------------
australia
united states
15223.0
------------
------------
australia
russia
48.2
------------
------------
canada
japan
382.5
------------
------------
canada
new zealand
160.9
------------
------------
canada
united states
33851.0
------------
------------
canada
russia
40.8
------------
------------
japan
korea
1263.4
------------
------------
japan
new zealand
488.6
------------
------------
japan
united states
13352.0
------------
------------
japan
russia
205.2
------------
------------
new zealand
united states
996.0
------------
------------
new zealand
russia
14.5
------------
------------
korea
united states
11578.0
------------
------------
russia
united states
4490.0
------------
------------
russia
lithuania
665.7
------------
------------
united states
lithuania
10.8
------------
386
3316
386

In [11]:
df_important_columns[(df_important_columns['Country'] == 'austria') & (df_important_columns['Partner'] == 'denmark')]

   Country  Partner  Value
5  austria  denmark  393.3

In [12]:
df_important_columns[(df_important_columns['Country'] == 'denmark') & (df_important_columns['Partner'] == 'austria')]

     Country  Partner  Value
161  denmark  austria  163.5

In [14]:
df_one_direction

        Country    Partner   Value
0       austria  australia    58.5
1       austria    belgium   507.5
2       austria     canada    99.6
3       austria      chile    45.2
4       austria    czechia   509.5
...         ...        ...     ...
4080  lithuania     serbia     0.1
4081  lithuania    ukraine     6.8
4083  lithuania      asean    38.9
4084      japan      asean  3778.1
4085    finland      asean   136.8

[3700 rows x 3 columns]

In [17]:
mapping_1 = {
    'united states': 'usa',     

    'china (people’s republic of)': 'china',

    'viet nam': 'vietnam',

    'slovak republic': 'slovakia',

    'türkiye': 'turkey',

    'papua new guinea': 'papuanewguinea',

    'south africa': 'southafrica',

    'new zealand': 'newzealand',

    'united arab emirates': 'uae',

    'united kingdom': 'uk',

    'czechrep': 'czechia',

    'brunei darussalam': 'brunei',

    'equatorial guinea': 'equatorialguinea',

    'south sudan': 'southsudan',

    'guinea-bissau': 'guineabissau',

    'burkina faso': 'burkinafaso',

    'syrian arab republic': 'syria',

    'san marino': 'sanmarino',

    'sierra leone': 'sierraleone',

    'costa rica': 'costarica',

    "korea, democratic people's republic of": 'sourthkorea',

    'korea': 'northkorea',

    'el salvador': 'elsalvador',

    'north macedonia': 'northmacedonia',

    'côte d’ivoire': 'ivorycoast',

    'marshall islands': 'marshallislands',

    'sao tome and principe': 'saotome',

    'bosnia and herzegovina': 'bosnia',

    'dominican republic': 'dominicanrepublic',

    'solomon islands': 'solomonislands',

    "lao people's democratic republic": 'laos',

    'antigua and barbuda': 'antiguaandbarbuda',

    'saudi arabia': 'saudiarabia',

    'sri lanka': 'srilanka',

    'saint kitts and nevis': 'stkitts',

    'saint lucia': 'saintlucia',

    'cape verde': 'capeverde',

    'micronesia, federated states of': 'micronesia',

    'hong kong (china)': 'china',

    'hong kong, china': 'china',
    
}

df_one_direction['Country'] = df_one_direction['Country'].replace(mapping_1)
df_one_direction['Partner'] = df_one_direction['Partner'].replace(mapping_1)

values_to_remove = {'asean', 'isle of man', 'cayman islands', 'pitcairn', 'serbia', 'gibraltar', 'faeroe islands', 'new caledonia', 'curaçao', 'macao (china)', 'saint helena', 'bermuda', 'guernsey', 'cocos (keeling) islands', 'british virgin islands', 'french polynesia', 'guam', 'british indian ocean territory', 'niue', 'norfolk island', 'south america', 'democratic republic of the congo', 'central african republic', 'jersey', 'virgin islands, united states', 'chinese taipei', 'montserrat', 'greenland', 'south georgia and the south sandwich islands'}

mask_to_keep = ~df_one_direction['Country'].isin(values_to_remove) & ~df_one_direction['Partner'].isin(values_to_remove)

df_one_direction = df_one_direction[mask_to_keep]

df_one_direction.to_csv('FINANSES_dataset.csv', index=False)

df_one_direction

        Country        Partner  Value
0       austria      australia   58.5
1       austria        belgium  507.5
2       austria         canada   99.6
3       austria          chile   45.2
4       austria        czechia  509.5
...         ...            ...    ...
4075  lithuania  liechtenstein    0.7
4076  lithuania          malta   65.9
4077  lithuania        moldova    1.2
4078  lithuania        romania   32.0
4081  lithuania        ukraine    6.8

[3287 rows x 3 columns]

In [18]:
df_organizations = pd.read_csv('ORGANIZATIONS_original.csv')

mapping_2 = {

    'soafrica': 'southafrica',

    'eqguinea': 'equatorialguinea',

    'sosudan': 'southsudan',

    'sokorea': 'sourthkorea',

    'nokorea': 'northkorea',

    'fyromacedonia': 'northmacedonia',

    'marshallis': 'marshallislands',

    'domrepublic': 'dominicanrepublic',

    'solomonis': 'solomonislands',

    'antiguabarbuda': 'antiguaandbarbuda',

    'congobrazz': 'congo',
    
    'stlucia': 'saintlucia',

    'micronesiafs': 'micronesia',

    'czechrep': 'czechia'
}

df_organizations['country1'] = df_organizations['country1'].replace(mapping_2)
df_organizations['country2'] = df_organizations['country2'].replace(mapping_2)

values_to_remove = {'tuscany', 'korea', 'zanzibar', 'syemen', 'hessegrand', 'parma', 'egermany', 'twosicilies', 'saxony', 'andorra', 'nyemen', 'yemen', 'car', 'tuvalu', 'seychelles', 'bavariaelect', 'monaco', 'wgermany', 'papalstates', 'stvincent', 'modena', 'vanuatu', 'baden', 'hesseelect', 'austriahungary', 'yugoslaviaserb', 'kosovo', 'mecklenburg', 'wurtenburg', 'nokorea', 'taiwan', 'zaire', 'svietnam', 'czechoslovakia', 'tonga', 'wsamoa', 'etimor', 'hanover', 'trinidad'}

mask_to_keep = ~df_organizations['country1'].isin(values_to_remove) & ~df_organizations['country2'].isin(values_to_remove)

df_organizations = df_organizations[mask_to_keep]

df_organizations.to_csv('ORGANIZATIONS_dataset.csv', index=False)

df_organizations

In [19]:
# df_sorted_high = df_one_direction.sort_values(by='Value', ascending=False)
# print(df_sorted_high.head(10))

In [20]:
# df_sorted_low = df_one_direction.sort_values(by='Value', ascending=True)
# print(df_sorted_low.head(10))

In [21]:
# DROPPING VERY LOW DATA

# df_reduced = df_one_direction[df_one_direction['Value'] >= 50]

# df_reduced.to_csv('df_reduced.csv', index=False)